# Generated by Django 3.0.7 on 2023-08-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0004_auto_20230731_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='business_domain',
            field=models.CharField(choices=[('HR', '人事'), ('FI', '财务'), ('AD', '行政'), ('MA', '市场'), ('BU', '商务'), ('CS', '客服'), ('OT', '其他'), ('PO', '采购')], default='OT', max_length=4, verbose_name='business domain'),
        ),
    ]
