# Generated by Django 3.0.7 on 2023-08-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0005_auto_20230802_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tp',
            field=models.CharField(blank=True, choices=[('10', '主物料'), ('20', '水电煤气'), ('30', '餐具'), ('40', '设备'), ('50', '车辆运输'), ('60', '办公用品'), ('70', '工具'), ('80', '服务'), ('11', '辅料')], default='10', max_length=2, null=True, verbose_name='mt type'),
        ),
    ]
