# Generated by Django 3.0.7 on 2023-08-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0008_auto_20230804_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='measure',
        ),
        migrations.AddField(
            model_name='material',
            name='measure',
            field=models.ManyToManyField(to='basedata.Measure', verbose_name='measure'),
        ),
    ]
