# Generated by Django 3.0.7 on 2023-08-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_auto_20200615_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='tp',
            field=models.CharField(blank=True, choices=[('10', '主物料'), ('20', '水电煤气'), ('30', '餐具'), ('40', '设备'), ('50', '车辆运输'), ('60', '办公用品'), ('70', '工具'), ('80', '服务'), ('11', '辅料')], default='10', max_length=2, null=True, verbose_name='mt type'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='cnt',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='out_cnt',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='out count'),
        ),
    ]
