# Generated by Django 3.0.7 on 2023-08-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20230731_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vo_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='invoice amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='py_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='pay amount'),
        ),
    ]
