# Generated by Django 3.0.7 on 2023-08-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20230731_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='invoice_type',
            field=models.CharField(choices=[('10', '普通发票'), ('20', '增值税专用发票'), ('30', '专业发票')], default='10', max_length=6, verbose_name='invoice type'),
        ),
    ]
