# Generated by Django 3.0.7 on 2023-08-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20230802_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='cnt',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='collection_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='collection amount'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='cnt',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='count'),
        ),
    ]
