# Generated by Django 3.0.7 on 2023-08-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow', '0003_alter_modal_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modal',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['purchase', 'invent', 'sale', 'selfhelp', 'hr']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
